name: Build and Deploy Quarkus App to Azure

on:
  push:
    branches:
      - main

jobs:

  build-backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
        
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: build with mvn
        run: ./mvnw package

      - name: Build docker image
        run: docker build -f src/main/docker/Dockerfile.jvm -t cloud-days-stefan:lastest .

      - name: Docker registry login
        run: echo "hallo"
