name: Build and Deploy next js to Azure

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy-front-end:
      runs-on: ubuntu-latest
      defaults:
        run:
          working-directory: ./frontend
  
      steps:
        - name: Checkout repository
          uses: actions/checkout@v4
  
        - name: Set up Node.js
          uses: actions/setup-node@v2
          with:
            node-version: '20.9.0'
  
        - name: Install dependencies
          run: npm install
  
        - name: Build
          run: npm run build  # Adjust build command if different
  
        - name: Deploy to Azure Static Web Apps
          uses: azure/static-web-apps-deploy@v1
          with:
            azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
            repo_token: ${{ secrets.GITHUB_TOKEN }}
            action: "upload"
            app_location: './frontend/.next'  # Path to your application code within the repository
            api_location: ''
            skip_api_build: true
            skip_app_build: true

